import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavLink } from "@/app/navbar/nav-link";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
            <html lang="en">
            <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
            <NavLink
                    prefetch={false}
                    href={"/directive-cache"}
                    activeState={
                        <span className="text-pink-600">activeState</span>
                    }
                    pendingState={
                        <span className="text-muted-foreground flex gap-2 items-center">pendingState</span>
                    }
            >
                NavLink
            </NavLink>
            <NavLink
                    prefetch={false}
                    href={"/directive-cache/1"}
                    activeState={
                        <span className="text-pink-600">show</span>
                    }
                    pendingState={
                        <span className="text-muted-foreground flex gap-2 items-center">showpendingState</span>
                    }
            >
                show
            </NavLink>
            {children}
            </body>
            </html>
    );
}
